version: '3.8'

services:
  app:
    image: testapp:local
    container_name: my-test-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my-network
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
#Need to change them to read from .env
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge